import JSZip from 'jszip';
import packSchema from '../../schemas/mapsoo-pack-0.6.schema.json';
import {
  ALPHA9_ATLAS_IDS,
  ALPHA9_LAYER_IDS,
  ALPHA9_PACK_SCHEMA_VERSION,
  ALPHA9_PACK_VERSION,
  assertAlpha9PackManifest,
  type Alpha9FileRecord,
  type Alpha9PackManifest,
} from '../core/pack-manifest-alpha9';
import { TOPDOWN_FARM_REQUIRED_ROLES } from '../core/generated-asset-bundle';
import { fingerprintGenerationRequestV2, type GenerationRequestV2 } from '../core/generation-request-v2';
import { projectWorldAssetReceipt } from '../core/world-asset-receipt';
import {
  assertTrustedWorldAssetGeneration,
  type WorldAssetGenerationResult,
} from '../core/world-asset-provider';
import {
  prepareWorldLayoutPackEntry,
  selectWorldLayoutAwarePackSchema,
  WORLD_LAYOUT_PACK_PATH,
} from '../core/world-layout-pack-binding';
import type { WorldLayoutPlan } from '../core/world-layout-plan';

const ZIP_DATE = new Date(Date.UTC(1980, 0, 1));

interface Entry { readonly path: string; readonly bytes: Uint8Array; readonly record: Alpha9FileRecord }

async function sha256(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', bytes.slice().buffer);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
}

function text(value: string): Uint8Array {
  return new TextEncoder().encode(value);
}

function json(value: unknown): Uint8Array {
  return text(`${JSON.stringify(value, null, 2)}\n`);
}

async function entry(path: string, mediaType: Alpha9FileRecord['media_type'], bytes: Uint8Array): Promise<Entry> {
  return { path, bytes, record: { path, media_type: mediaType, bytes: bytes.byteLength, sha256: await sha256(bytes) } };
}

export interface Alpha9PortablePack {
  readonly filename: string;
  readonly bytes: Uint8Array;
  readonly manifest: Alpha9PackManifest;
}

export async function buildAlpha9WorldAssetPack(
  run: WorldAssetGenerationResult,
  request: GenerationRequestV2,
  completedAt: string,
  layoutPlan?: WorldLayoutPlan,
): Promise<Alpha9PortablePack> {
  assertTrustedWorldAssetGeneration(run);
  if (run.requestId !== request.id || request.profile !== 'topdown-farm') {
    throw new Error('Alpha.9 export requires the matching topdown-farm request.');
  }
  if (await fingerprintGenerationRequestV2(request) !== run.requestFingerprintSha256) {
    throw new Error('Alpha.9 export request fingerprint does not match the trusted generation run.');
  }
  if (request.references.some(({ rights }) => (
    rights.basis !== 'owned' || rights.allowOutputCc0Dedication !== true
  ))) {
    throw new Error('Alpha.9 CC0 export requires user-owned references with explicit CC0 dedication permission.');
  }
  const receipt = await projectWorldAssetReceipt(run, request, completedAt);
  const preparedLayout = layoutPlan === undefined
    ? undefined
    : await prepareWorldLayoutPackEntry(layoutPlan, request.profile, request.seed);
  const generatedEntries = await Promise.all(run.payloads.map(async (payload) => {
    const bytes = payload.readBytes();
    return entry(payload.path, payload.mediaType, bytes);
  }));
  const supportEntries = await Promise.all([
    entry('generation-receipt.json', 'application/json', json(receipt)),
    entry(
      'schema/mapsoo-pack-0.6.schema.json',
      'application/schema+json',
      json(selectWorldLayoutAwarePackSchema(packSchema, Boolean(preparedLayout))),
    ),
    entry('license-assets.md', 'text/markdown', text(
      '# Asset license\n\nThe generated PNG and runtime JSON assets in this pack are dedicated under CC0-1.0.\n\nReference images are not included and remain under their original rights. The schema and documentation are distributed under the repository MIT license.\n',
    )),
    entry('readme.md', 'text/markdown', text(
      `# ${request.id}\n\nComplete top-down farm source asset pack generated by Mapsoo Worldsmith ${ALPHA9_PACK_VERSION}.\n\nIncludes terrain, props, structures, four crop stages, a four-direction player, collision, navigation, scene data and preview. Install the Mapsoo Godot importer and select mapsoo.manifest.json.\n`,
    )),
  ]);
  const layoutEntries = preparedLayout
    ? [await entry(WORLD_LAYOUT_PACK_PATH, 'application/json', preparedLayout.bytes)]
    : [];
  const entries = [...generatedEntries, ...supportEntries, ...layoutEntries].sort((left, right) => left.path.localeCompare(right.path, 'en'));
  const assetPath = new Map(run.bundle.assets.map((asset) => [asset.id, asset.path]));
  const rolePath = new Map(run.bundle.roles.map((role) => [role.role, assetPath.get(role.assetId) ?? '']));
  const character = run.bundle.characters[0];
  const atlasPaths = {
    terrain: rolePath.get('terrain.ground') ?? '',
    props: rolePath.get('prop.tree') ?? '',
    structures: rolePath.get('structure.house') ?? '',
    crops: rolePath.get('crop.basic.stage-1') ?? '',
    character: rolePath.get('character.player.atlas') ?? '',
  } as const;
  const manifest: Alpha9PackManifest = {
    schema_version: ALPHA9_PACK_SCHEMA_VERSION,
    pack: {
      id: request.id, title: request.id, version: ALPHA9_PACK_VERSION,
      generator: { name: 'Mapsoo Worldsmith', version: ALPHA9_PACK_VERSION }, created_at: completedAt,
    },
    profile: 'topdown-farm',
    completeness_policy: 'topdown-farm-complete-v1',
    compatibility: {
      godot_min: '4.3', grid: 'orthogonal', art_style: 'pixel_art',
      importer: { id: 'mapsoo_importer', min_version: ALPHA9_PACK_VERSION },
    },
    layers: ALPHA9_LAYER_IDS.map((id, order) => ({ id, order })),
    atlases: ALPHA9_ATLAS_IDS.map((id) => ({ id, path: atlasPaths[id] })),
    roles: TOPDOWN_FARM_REQUIRED_ROLES.map((role) => ({ role, path: rolePath.get(role) ?? '' })),
    character: {
      id: character.id, atlas: atlasPaths.character,
      frame_size: [character.frameWidth, character.frameHeight], pivot: character.pivot,
      clips: character.clips.map((clip) => {
        // Alpha9's trusted farm validator has already proven this narrower matrix.
        const action = clip.action as 'idle' | 'walk';
        const direction = clip.direction as 'north' | 'east' | 'south' | 'west';
        return {
          id: `${action}.${direction}` as const, action, direction,
          fps: clip.fps, frames: clip.frames.map((frame) => ({ x: frame.x, y: frame.y })),
        };
      }),
    },
    runtime: {
      scene: { path: assetPath.get(run.bundle.scene.dataAssetId) ?? '' },
      collision: { path: assetPath.get(run.bundle.scene.collisionAssetId) ?? '' },
      navigation: { path: assetPath.get(run.bundle.scene.navigationAssetId) ?? '' },
      spawn: run.bundle.scene.spawn,
    },
    ...(preparedLayout ? { layout: preparedLayout.binding } : {}),
    files: entries.map(({ record }) => record),
    license: { output: { id: 'CC0-1.0', notice_path: 'license-assets.md', permits_redistribution: true } },
    provenance: {
      provider: { id: run.provider.id, version: run.provider.version },
      output_provenance: 'procedural', contains_generative_ai: false, model_provider: null, model: null,
      seed: request.seed, human_curated: false,
    },
  };
  assertAlpha9PackManifest(manifest);
  const root = `mapsoo-${request.id}-v${ALPHA9_PACK_VERSION}`;
  const archive = new JSZip();
  const archiveEntries = [
    ...entries.map(({ path, bytes }) => ({ path: `${root}/${path}`, bytes })),
    { path: `${root}/mapsoo.manifest.json`, bytes: json(manifest) },
  ].sort((left, right) => left.path.localeCompare(right.path, 'en'));
  for (const item of archiveEntries) {
    archive.file(item.path, item.bytes, { binary: true, createFolders: false, date: ZIP_DATE, unixPermissions: 0o100644 });
  }
  const bytes = await archive.generateAsync({
    type: 'uint8array', compression: 'DEFLATE', compressionOptions: { level: 9 }, platform: 'UNIX', streamFiles: false,
  });
  return Object.freeze({ filename: `${root}.zip`, bytes, manifest });
}
